name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge::pandas=0.24.2
  - conda-forge::numpy=1.16.2
  - conda-forge::regex=2019.11.1
  - conda-forge::pytz=2019.3
  - conda-forge::pyzmq=18.0.1
  - pip:
    - tzwhere==3.0.3
    - datefinder==0.7.0
    - DateTime==4.3
